############# English navigation ##############

# main menu
[[main]]
name = "About"
url = "about/"
weight = 2

# main menu
[[main]]
name = "Tech Events"
url = "https://utahdev.events"
weight = 4

# [[main]]
# name = "Elements"
# url = "elements/"
# weight = 3



[[main]]
weight = 3
name = "Community"
hasChildren = true

[[main]]
parent = "Community"
name = "Meetups"
url = "meetups/"
weight = 1

[[main]]
parent = "Community"
name = "Roundtables"
url = "roundtables"
weight = 2

[[main]]
parent = "Community"
name = "Go West Conference"
url = "gowest/"
weight = 3








# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
weight = 5
name = "Blog"
url = "blog/"

[[footer]]
weight = 6
name = "Contact"
url = "contact/"
