############# English navigation ##############

# main menu
[[main]]
name = "About"
url = "about/"
weight = 2

# main menu
[[main]]
name = "Tech Events"
url = "events/"
weight = 3

# [[main]]
# name = "Elements"
# url = "elements/"
# weight = 3



[[main]]
weight = 4
name = "Community"
hasChildren = true


[[main]]
parent = "Community"
name = "Meetups"
url = "meetups/"

[[main]]
parent = "Community"
name = "Go West Conference"
url = "gowest/"

[[main]]
parent = "Community"
name = "Roundtables"
url = "roundtables"






# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Elements"
url = "elements/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3

[[footer]]
weight = 5
name = "Blog"
url = "blog/"

[[footer]]
weight = 6
name = "Contact"
url = "contact/"
